spring:
  application:
    name: eureka-producer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${random.value}

